# Generated by Django 3.2.12 on 2022-08-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categ_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'categ', 'verbose_name_plural': 'categories'},
        ),
    ]
