# Generated by Django 3.2.12 on 2022-08-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartlist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='items',
            name='prod',
        ),
        migrations.DeleteModel(
            name='cartlist',
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
